### ISSUE TITLE
Issue when executing playbook

### ISSUE THREAD

**Issue by ruday1** [btotharye/ansible-ucs#3]
[08:03 root@localhost ansible-ucs-brian] > ansible-playbook -i inventory site.yml

PLAY [ucs] *********************************************************************

TASK [admin : Add NTP Entry 10.106.31.211] *************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named library.ucs
fatal: [UCSM-PE]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_4v04SE/ansible_module_ucs_ntp.py\", line 55, in <module>\n    from library.ucs import UCS\nImportError: No module named library.ucs\n", "module_stdout": "", "msg": "MODULE FAILURE"}
        to retry, use: --limit @/usr/ruday-ans-scripts/ansible-ucs-brian/site.retry

PLAY RECAP *********************************************************************
UCSM-PE                    : ok=0    changed=0    unreachable=0    failed=1

[08:03 root@localhost ansible-ucs-brian] > ls
docs  group_vars  inventory  library  plays  README.md  roles  site.retry  site.yml
[08:03 root@localhost ansible-ucs-brian] > cat inventory
[ucs]
UCSM-PE ucsm_ip=10.106.31.211 ucsm_login=root ucsm_pw=cisco123
[08:03 root@localhost ansible-ucs-brian] >

Please take a look

Thanks,
- Ravi

**Comment by btotharye** [comment]
Was related to missing env variables.  Closing
